# image: google/cloud-sdk:latest
stages:
  - test
  - build
  - deploy
  - production

image: docker:latest
services:
  - docker:dind

variables:
  CONTAINER_IMAGE: leandro2m/app-python:${CI_COMMIT_SHORT_SHA}

before_script:

SAST:
  image: registry.fortidevsec.forticloud.com/fdevsec_sast:latest
  stage: test
  script:
    - main
build:
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}
deploy:
    stage: deploy
    image: google/cloud-sdk:latest
    script:
      - echo $KUBE_TOKEN | base64 --decode > ./kube_token
      - echo $KUBE_CA | base64 --decode > ./kube_ca
      - kubectl config set-cluster k8s --server=${SERVER} --certificate-authority="$(pwd)/kube_ca"
      - kubectl config set-credentials gitlab --token="$(cat ./kube_token)"
      - kubectl config set-context development --cluster=k8s --user=gitlab
      - kubectl config use-context development
      - kubectl set image deployment/app-python app-python=${CONTAINER_IMAGE}
DAST:
  image: registry.fortidevsec.forticloud.com/fdevsec_dast:latest
  stage: production
  script:
    - main
