apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  labels:
    app: demo-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app
          image: leandro2m/demo-app:30
          ports:
          - name: backend-port
            containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: true
---
