apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-demo-app
  name: service-demo-app
  namespace: default
spec:
  ports:
  - name: backend-app-http
    port: 80
    protocol: TCP
    targetPort: backend-port
  selector:
    app: demo-app
  type: LoadBalancer